// <auto-generated />
using System;
using FincaFenix.EFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FincaFenix.EFCore.Migrations
{
    [DbContext(typeof(FincaFenixContext))]
    [Migration("20250711162357_HectareasxSectorFinca")]
    partial class HectareasxSectorFinca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.CorrelativeNumberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LastNumber")
                        .HasColumnType("int")
                        .HasColumnName("Numero");

                    b.Property<string>("TypeDoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoDoc");

                    b.HasKey("Id");

                    b.ToTable("Correlativo", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.DetailRecipeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountRequired")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CantRequerida");

                    b.Property<string>("AmountRequiredUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UnidadCantRequerida");

                    b.Property<decimal>("EstimatedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CantEstimada");

                    b.Property<string>("EstimatedAmountUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UnidadCantEstimada");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("IdMaterial");

                    b.Property<int>("RecipeId")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("IdReceta");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("RecipeId");

                    b.ToTable("DetalleReceta", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.DetailSectorFarmEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Hectareas");

                    b.Property<int>("FarmId")
                        .HasColumnType("int")
                        .HasColumnName("IdFinca");

                    b.Property<int?>("NumberPlants")
                        .HasColumnType("int")
                        .HasColumnName("CantPlantas");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreCuadro");

                    b.Property<int?>("VarietyId")
                        .HasColumnType("int")
                        .HasColumnName("IdVariedad");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("VarietyId");

                    b.ToTable("DetalleSectorFinca", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.DetailWorkOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaActividad");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("IdEmpleado");

                    b.Property<decimal>("Performance")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Rendimiento");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<int>("SectorWorkedId")
                        .HasColumnType("int")
                        .HasColumnName("IdSectorTrabajado");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("IdOrdenTrabajo");

                    b.Property<decimal>("WorkedHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("HorasTrabajadas");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SectorWorkedId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("DetalleOrdenTrabajo", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.DiseasePlagueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("EnfermedadPlaga", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.DiseasePlague_MaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEnfermedadPlagaMaterial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiseasePlagueId")
                        .HasColumnType("int")
                        .HasColumnName("IdEnfermedadPlaga");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("IdMaterial");

                    b.HasKey("Id");

                    b.HasIndex("DiseasePlagueId");

                    b.HasIndex("MaterialId");

                    b.ToTable("EnfermedadPlaga_Material", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.Employee_FarmEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdEmpleadoFinca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("IdEmpleado");

                    b.Property<int>("FarmId")
                        .HasColumnType("int")
                        .HasColumnName("IdFinca");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FarmId");

                    b.ToTable("Empleado_Finca", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.FarmEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Eliminado");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Finca", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.FruitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Frutal");

                    b.HasKey("Id");

                    b.ToTable("Frutal", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.FruitVarietyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("VariedadFruta");

                    b.Property<int>("FruitId")
                        .HasColumnType("int")
                        .HasColumnName("IdFruta");

                    b.HasKey("Id");

                    b.HasIndex("FruitId");

                    b.ToTable("VariedadFrutal", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.MachineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Capacidad");

                    b.Property<string>("CapacityUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UnidadCapacidad");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Eliminado");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Maquinaria", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.MaterialCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.MaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NombreArticulo");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Marca");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("IdCategoria");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NombreComercial");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Eliminado");

                    b.Property<string>("PackingUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UnidadEmpaque");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Material", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.RecipeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Dosage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Dosis");

                    b.Property<string>("DosageUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UnidadDosis");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Eliminado");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("IdMaquina");

                    b.Property<string>("NumRecipe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumReceta");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Receta", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.RolEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Eliminado");

                    b.HasKey("Id");

                    b.ToTable("Tarea", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Eliminado");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Contrasena");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("Rol");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreUsuario");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.WorkOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2(2)")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2(2)")
                        .HasColumnName("FechaFin");

                    b.Property<int>("FarmId")
                        .HasColumnType("int")
                        .HasColumnName("IdFinca");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Eliminado");

                    b.Property<string>("OrderNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumOrden");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("IdReceta");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("datetime2(2)")
                        .HasColumnName("FechaInicio");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado");

                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("IdTarea");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("RecipeId")
                        .IsUnique()
                        .HasFilter("[IdReceta] IS NOT NULL");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("OrdenTrabajo", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.WorkOrderWorkedSectorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SectorFarmId")
                        .HasColumnType("int")
                        .HasColumnName("IdSector");

                    b.Property<int?>("WorkOrderEntityId")
                        .HasColumnType("int");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("IdOrdenTrabajo");

                    b.HasKey("Id");

                    b.HasIndex("SectorFarmId");

                    b.HasIndex("WorkOrderEntityId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("OrdenTrabajo_SectorTrabajado", (string)null);
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.DetailRecipeEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.MaterialEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincaFenix.Entities.POCOEntities.RecipeEntity", "Recipe")
                        .WithMany("DetailRecipeList")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.DetailSectorFarmEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.FarmEntity", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincaFenix.Entities.POCOEntities.FruitVarietyEntity", "Variety")
                        .WithMany()
                        .HasForeignKey("VarietyId");

                    b.Navigation("Farm");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.DetailWorkOrderEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.EmployeeEntity", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincaFenix.Entities.POCOEntities.DetailSectorFarmEntity", "SectorWorked")
                        .WithMany()
                        .HasForeignKey("SectorWorkedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincaFenix.Entities.POCOEntities.WorkOrderEntity", "WorkOrder")
                        .WithMany("DetailWorkOrderList")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("SectorWorked");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.DiseasePlague_MaterialEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.DiseasePlagueEntity", "DiseasePlague")
                        .WithMany("MaterialDiseasePlagueList")
                        .HasForeignKey("DiseasePlagueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FincaFenix.Entities.POCOEntities.MaterialEntity", "Material")
                        .WithMany("DiseasePlagueMaterialList")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DiseasePlague");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.Employee_FarmEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.EmployeeEntity", "Employee")
                        .WithMany("EmployeeList")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FincaFenix.Entities.POCOEntities.FarmEntity", "Farm")
                        .WithMany("FarmList")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.FruitVarietyEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.FruitEntity", "Fruit")
                        .WithMany()
                        .HasForeignKey("FruitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fruit");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.MaterialEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.MaterialCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.RecipeEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.MachineEntity", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.UserEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.RolEntity", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.WorkOrderEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.FarmEntity", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincaFenix.Entities.POCOEntities.RecipeEntity", "Recipe")
                        .WithOne()
                        .HasForeignKey("FincaFenix.Entities.POCOEntities.WorkOrderEntity", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FincaFenix.Entities.POCOEntities.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincaFenix.Entities.POCOEntities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Farm");

                    b.Navigation("Recipe");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.WorkOrderWorkedSectorEntity", b =>
                {
                    b.HasOne("FincaFenix.Entities.POCOEntities.DetailSectorFarmEntity", "SectorFarm")
                        .WithMany()
                        .HasForeignKey("SectorFarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FincaFenix.Entities.POCOEntities.WorkOrderEntity", null)
                        .WithMany("WorkedSectors")
                        .HasForeignKey("WorkOrderEntityId");

                    b.HasOne("FincaFenix.Entities.POCOEntities.WorkOrderEntity", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SectorFarm");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.DiseasePlagueEntity", b =>
                {
                    b.Navigation("MaterialDiseasePlagueList");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.EmployeeEntity", b =>
                {
                    b.Navigation("EmployeeList");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.FarmEntity", b =>
                {
                    b.Navigation("FarmList");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.MaterialEntity", b =>
                {
                    b.Navigation("DiseasePlagueMaterialList");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.RecipeEntity", b =>
                {
                    b.Navigation("DetailRecipeList");
                });

            modelBuilder.Entity("FincaFenix.Entities.POCOEntities.WorkOrderEntity", b =>
                {
                    b.Navigation("DetailWorkOrderList");

                    b.Navigation("WorkedSectors");
                });
#pragma warning restore 612, 618
        }
    }
}
